# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/andre/OneDrive/Desktop/Sistema/.Xil/Vivado-28100-Benjamin-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/ip/ila_0/hdl/verilog
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/d47c/hdl
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/ec67/hdl
    C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/ip/clk_wiz_0
    C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/ip/clk_wiz_1_1
  } {
      C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/ip/ila_0/hdl/verilog
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/d47c/hdl
    c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/ec67/hdl
    C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/ip/clk_wiz_0
    C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/ip/clk_wiz_1_1
  } {
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_processing_system7_0_0/synth/UART_Transfer_processing_system7_0_0.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/2ccb/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/676c/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/d59d/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_auto_pc_0/synth/UART_Transfer_auto_pc_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/andre/OneDrive/Desktop/Sistema/.Xil/Vivado-28100-Benjamin-PC/realtime/ila_0_stub.vhdl
      C:/Users/andre/OneDrive/Desktop/Sistema/.Xil/Vivado-28100-Benjamin-PC/realtime/clk_wiz_0_stub.vhdl
      C:/Users/andre/OneDrive/Desktop/Sistema/.Xil/Vivado-28100-Benjamin-PC/realtime/clk_wiz_1_stub.vhdl
      C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/new/PWM.vhd
      C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/new/glitch_ctrl.vhd
      C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.srcs/sources_1/new/counter_clock.vhd
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_axi_gpio_0_0/synth/UART_Transfer_axi_gpio_0_0.vhd
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_rst_ps7_0_100M_0/synth/UART_Transfer_rst_ps7_0_100M_0.vhd
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_clock_out_top_0_0/synth/UART_Transfer_clock_out_top_0_0.vhd
      c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/synth/UART_Transfer.vhd
      C:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/hdl/UART_Transfer_wrapper.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_3 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_5 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_34 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/376d/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_8 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/09bd/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_10 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/1443/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_15 c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top UART_Transfer_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/andre/OneDrive/Desktop/Sistema/.Xil/Vivado-28100-Benjamin-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
