# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/UART_Transfer/UART_Transfer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer || ORIG_REF_NAME==UART_Transfer} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_processing_system7_0_0/UART_Transfer_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_processing_system7_0_0 || ORIG_REF_NAME==UART_Transfer_processing_system7_0_0} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_axi_gpio_0_0/UART_Transfer_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_axi_gpio_0_0 || ORIG_REF_NAME==UART_Transfer_axi_gpio_0_0} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_ps7_0_axi_periph_0/UART_Transfer_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_ps7_0_axi_periph_0 || ORIG_REF_NAME==UART_Transfer_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_rst_ps7_0_100M_0/UART_Transfer_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_rst_ps7_0_100M_0 || ORIG_REF_NAME==UART_Transfer_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_clock_out_top_0_0/UART_Transfer_clock_out_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_clock_out_top_0_0 || ORIG_REF_NAME==UART_Transfer_clock_out_top_0_0} -quiet] -quiet

# IP: ip/ila_0_2/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/clk_wiz_1_1/clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: bd/UART_Transfer/ip/UART_Transfer_auto_pc_0/UART_Transfer_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_Transfer_auto_pc_0 || ORIG_REF_NAME==UART_Transfer_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_processing_system7_0_0/UART_Transfer_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==UART_Transfer_processing_system7_0_0 || ORIG_REF_NAME==UART_Transfer_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_axi_gpio_0_0/UART_Transfer_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==UART_Transfer_axi_gpio_0_0 || ORIG_REF_NAME==UART_Transfer_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_axi_gpio_0_0/UART_Transfer_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_axi_gpio_0_0/UART_Transfer_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==UART_Transfer_axi_gpio_0_0 || ORIG_REF_NAME==UART_Transfer_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_rst_ps7_0_100M_0/UART_Transfer_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==UART_Transfer_rst_ps7_0_100M_0 || ORIG_REF_NAME==UART_Transfer_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_rst_ps7_0_100M_0/UART_Transfer_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==UART_Transfer_rst_ps7_0_100M_0 || ORIG_REF_NAME==UART_Transfer_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/ip/UART_Transfer_auto_pc_0/UART_Transfer_auto_pc_0_ooc.xdc

# XDC: c:/Users/andre/OneDrive/Desktop/Sistema/counter_clock.gen/sources_1/bd/UART_Transfer/UART_Transfer_ooc.xdc
